##
##  █▀▄ █▀█ █▀█ █▀▀ ▄▀█ █▀█ █
##  █▄▀ █▄█ █▀▀ ██▄ █▀█ █▀▀ █
##
## this project is stored at Github.com/Hptlo/DopeAPI
## check out other projects if you are interested!
##
##
## CONFIG:
## all developer features are marked as *dev
## other features marked as *o
## language features are stored in lang.yml
##

## writes messages if some things happen like (file [FILE] was created at : [PATH]) or ([WARNING] Location couldn't be set)
## *o
debug: false

## the end there's nothing more































## like i said there is no more